args_filename = ""
base_path = "/home/andrew/"
#base_path = "/tmp"
mode = "file"
#mode = "socket"
#events_filename_0 = "dv-runtime.sock"
events_filename_0 = "dvSave-2023_03_10_10_51_30.aedat4"
events_filename_1 = "dv-runtime2.sock"
start_c = 0.30344322344322345
optimize_c = true
optimize_c_frequency = 1
optimize_controller = false
deblur_only = true
events_only = true
simulate_packet_latency = false
target_latency = 1000.0
show_display = true
show_blurred_display = true
output_fps = 2500
write_video = false
