args_filename = ""
base_path = "/home/andrew/"
#base_path = "/tmp"
mode = "file"
#mode = "socket"
#events_filename_0 = "dv-runtime.sock"
events_filename_0 = "dvSave-2023_01_23_12_09_23.aedat4"
events_filename_1 = "dv-runtime2.sock"
start_c = 0.30344322344322345
optimize_c = true
optimize_c_frequency = 1
optimize_controller = false
deblur_only = true
events_only = false
simulate_packet_latency = false
target_latency = 1000.0
show_display = false
show_blurred_display = false
output_fps = 500
write_video = false
