args_filename = ""
scale = 1.0
input_filename= "/home/andrew/Videos/IMG_1150.mp4"
output_raw_video_filename = "/home/andrew/Videos/output_recon.mp4"
output_events_filename = "/home/andrew/Videos/output.adder"
c_thresh_pos = 10
c_thresh_neg = 10
color_input = true
show_display = true
frame_idx_start = 0
ref_time = 255     # Ticks per input frame
delta_t_max = 2550
frame_count_max = 3000
thread_count = 8
time_mode = "absolute"