args_filename = ""
scale = 0.50
input_filename= "/home/andrew/Videos/VIRAT_S_050201_05_000890_000944.mp4"
output_raw_video_filename = "/home/andrew/Videos/output_recon.mp4"
output_events_filename = "/home/andrew/Videos/output.adder"
crf = 3
color_input = false
show_display = true
frame_idx_start = 0
ref_time = 255     # Ticks per input frame
delta_t_max = 7650
frame_count_max = 500
thread_count = 16
time_mode = "absolute"
integration_mode = "collapse"