[package]
name = "adder-codec-rs"
version = "0.1.4"
edition = "2021"
authors = ["Andrew C. Freeman"]
description = """Encoder/transcoder/decoder for ADΔER (Address, Decimation, Δt Event Representation) streams.
 Currently, only implemented for raw (uncompressed) streams. Includes a transcoder for """
homepage = "https://github.com/ac-freeman/adder-codec-rs"
repository = "https://github.com/ac-freeman/adder-codec-rs"
readme = "README.md"
license-file = "LICENSE"
keywords = ["neuromorphic", "decoding", "event", "asynchronous", "video"]
categories = ["multimedia::encoding", "science"]
exclude = [
    "tests/samples/*",
]

[profile.release]
lto = true

[dependencies]
rand = "0.8.5"
itertools = "0.10.3"
duplicate = "0.4.1"
serde = {version = "1.0.140", features = ["derive"]}
serde_bytes = "0.11.6"
bincode = "1.3.3"
rayon = "1.5.3"
num = "0.4"
ndarray = {version = "0.15.6", features = ["rayon", "serde"]}
opencv = {version = "0.63.1", optional = true}
fast-math = {version = "0.1", optional = true}

[features]
default = ["transcoder"]
transcoder = ["dep:opencv", "dep:fast-math"]

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 2
