[workspace]
resolver = "2"
members = [
    "adder-codec-rs",
]

[profile.release]
lto = true
opt-level = 3

[profile.dev.package."*"]
opt-level = 2

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 0