[package]
name = "adder-codec-core"
version = "0.1.1"
edition = "2021"
authors = ["Andrew C. Freeman"]
description = """Encoder/transcoder/decoder for ADΔER (Address, Decimation, Δt Event Representation) streams.
 Currently, only implemented for raw (uncompressed) streams. Includes a transcoder for casting either framed or event video
 into an ADΔER representation in a manner which preserves the temporal resolution of the source.
 """
homepage = "https://github.com/ac-freeman/adder-codec-rs/wiki"
repository = "https://github.com/ac-freeman/adder-codec-rs"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["neuromorphic", "decoding", "event", "asynchronous", "video"]
categories = ["multimedia::encoding", "multimedia::video", "science"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
bitstream-io = "1.6.0"
num-traits = "0.2.15"
serde = { version = "1.0.140", features = ["derive"] }
serde_bytes = "0.11.6"
serde_json = "1.0"
thiserror = "1.0.38"