[package]
name = "adder-codec-rs"
version = "0.2.6"
edition = "2021"
authors = ["Andrew C. Freeman"]
description = """Encoder/transcoder/decoder for ADΔER (Address, Decimation, Δt Event Representation) streams.
 Currently, only implemented for raw (uncompressed) streams. Includes a transcoder for casting either framed or event video
 into an ADΔER representation in a manner which preserves the temporal resolution of the source.
 """
homepage = "https://github.com/ac-freeman/adder-codec-rs/wiki"
repository = "https://github.com/ac-freeman/adder-codec-rs"
readme = "../README.md"
license = "MIT OR Apache-2.0"
keywords = ["neuromorphic", "decoding", "event", "asynchronous", "video"]
categories = ["multimedia::encoding", "multimedia::video", "science"]
exclude = [
    "tests/samples/*",
]
default-run = "adder_simulproc"

[features]
default = ["transcoder"]
transcoder = ["opencv", "dep:fast-math"]
raw-codec = []
docs-only = ["opencv/docs-only", "dep:fast-math"]

[dependencies.opencv]
version = '0.66.0'
package = 'opencv'
default-features = false
features = ['videoio', 'imgproc', 'highgui']
optional = true

[dependencies]
rand = "0.8.5"
itertools = "0.10.3"
duplicate = "0.4.1"
float-cmp = "0.9.0"
serde = {version = "1.0.140", features = ["derive"]}
serde_json = "1.0"
serde_bytes = "0.11.6"
bincode = "1.3.3"
rayon = "1.5.3"
num = "0.4"
ndarray = {version = "0.15.6", features = ["rayon", "serde"]}
fast-math = {version = "0.1", optional = true}
reqwest = "0.11.11"
tokio = {version = "1.20.1", features = ["full"]}
clap = { version = "4.0.17", features = ["derive"] }
generational-arena = "0.2"
smallvec = "1.9.0"
bumpalo = "3.11.0"
davis-edi-rs = "0.1.6"
#davis-edi-rs = { path = "../../davis-EDI-rs" }
toml = "0.5.8"
aedat = "1.2.7"
num-traits = "0.2.15"

[dev-dependencies]
criterion = "0.3.6"
criterion-perf-events = "0.2.0"
perfcnt = "0.8.0"

[[bench]]
name = "framed_to_adder_hd"
harness = false

[package.metadata.docs.rs]
no-default-features = true
default-target = "x86_64-unknown-linux-gnu"
features = ["docs-only"]
