args_filename = ""
edi_args_filename = "./src/bin/args/edi_args.toml"
output_events_filename = "/home/andrew/Downloads/davis.adder"
adder_c_thresh_pos = 10
adder_c_thresh_neg = 10
delta_t_max_multiplier = 1.0
transcode_from = "raw"
#transcode_from = "framed"
show_display = 1
optimize_adder_controller = 1