args_filename = ""
edi_args_filename = "./src/bin/args/edi_args.toml"
output_events_filename = "/home/andrew/Downloads/davis.adder"
adder_c_thresh_pos = 10
adder_c_thresh_neg = 10
delta_t_max_multiplier = 10.0
transcode_from = "raw-davis"
#transcode_from = "framed"
show_display = true
write_out = true
optimize_adder_controller = true