args_filename = ""
base_path = "/media/andrew/ExternalM2/Dayton_DAVIS_dataset_2/1_aedat/"
#base_path = "/tmp"
mode = "file"
#mode = "socket"
#events_filename_0 = "dv-runtime.sock"
events_filename_0 = "alley-2019_11_04_09_36_15.aedat4"
events_filename_1 = "dv-runtime2.sock"
start_c = 0.30344322344322345
optimize_c = true
optimize_controller = false
deblur_only = true
events_only = false
simulate_packet_latency = true
target_latency = 1000.0
show_display = true
show_blurred_display = false
output_fps = 30000
write_video = false
