args_filename = ""
scale = 1.0
input_filename= "/home/andrew/Downloads/IMG_6772.MOV"
output_raw_video_filename = "/home/andrew/Downloads/rockies"
output_events_filename = "/home/andrew/Downloads/rockies.adder"
c_thresh_pos = 10
c_thresh_neg = 10
color_input = true
show_display = true
frame_idx_start = 0
ref_time = 255     # Ticks per input frame
delta_t_max = 38250
frame_count_max = 0
thread_count = 16