args_filename = ""
scale = 1.0
input_filename= "/media/andrew/Scratch/ugc-dataset/original_videos_h264/Animation_360P-08c9_crf_10_ss_00_t_20.0.mp4"
output_raw_video_filename = "/home/andrew/Downloads/anim_out"
tps = 300000
fps = 30
output_events_filename = ""
c_thresh_pos = 15
c_thresh_neg = 15
color_input = 1
show_display = 1
frame_idx_start = 0
ref_time = 5000
delta_t_max = 300000
frame_count_max = 0
thread_count = 16