args_filename = ""
scale = 1.0
input_filename= "/home/andrew/Downloads/lake_scaled_hd_trimmed.mp4"
output_raw_video_filename = "/home/andrew/Downloads/anim_out_0"
output_events_filename = ""
c_thresh_pos = 0
c_thresh_neg = 0
color_input = false
show_display = true
frame_idx_start = 0
ref_time = 100     # Ticks per input frame
delta_t_max = 12000
frame_count_max = 0
thread_count = 16