args_filename = ""
scale = 1.0
input_filename= "/home/andrew/Code/davis-EDI-rs/output_file.mp4"
output_raw_video_filename = "/home/andrew/Downloads/waves_out"
tps = 150000
fps = 30
output_events_filename = ""
c_thresh_pos = 15
c_thresh_neg = 15
color_input = 1
show_display = 0
frame_idx_start = 0
ref_time = 5000
delta_t_max = 150000
frame_count_max = 0
thread_count = 16