name: Build and test adder-info

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  src:
    strategy:
      fail-fast: false
      matrix:
        os:
          - image: ubuntu-20.04
            family: linux
        rust:
          - stable
          - beta
        version:
          - opencv: 4.6.0
        exclude:
          - os:
              family: osx
            version:
              opencv: 3.4.17
    runs-on: ${{ matrix.os.image }}
    env:
      OS_FAMILY: ${{ matrix.os.family }}
      RUST_TOOLCHAIN: ${{ matrix.rust }}
      Atlas_ROOT_DIR: /usr/include/ # for cmake to find lapacke.h
      OPENCV_VERSION: ${{ matrix.version.opencv }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/build
          key: ${{ runner.os }}-${{ matrix.version.opencv }}-build

      - name: Install dependencies
        run: adder-info/ci/install.sh
        shell: bash

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          
      - name: Test project
        run: adder-info/ci/script.sh
        shell: bash

  bin:
    strategy:
      fail-fast: false
      matrix:
        os:
          - image: ubuntu-20.04
            family: linux
        rust:
          - stable
          - beta
        version:
          - branch: 4
            opencv: 4.5.5
            brew: "@4"
        include:
          - os:
              image: ubuntu-20.04
              family: linux
            rust: stable
            version:
              opencv: 4.2.0
              brew: excluded
    runs-on: ${{ matrix.os.image }}
    env:
      OS_FAMILY: ${{ matrix.os.family }}
      RUST_TOOLCHAIN: ${{ matrix.rust }}
      OPENCV_VERSION: ${{ matrix.version.opencv }}
      BREW_OPENCV_VERSION: ${{ matrix.version.brew }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: adder-info/ci/install.sh
        shell: bash

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Test project
        run: adder-info/ci/script.sh
        shell: bash
